const ProductData = [
    {
        id: appleWatch,
        Title: 'Apple Watch',
        img: './ProductImages/apple-watch.png',
        Price: 529.99,
        Des: "Apple Watch can do what your other devices can’t because it’s on your wrist. When you wear it, you get a fitness partner that measures all the ways you move, meaningful health insights, innovative safety features, and a connection to the people you care about most.",
    },
    {
        id: headphones,
        Title: 'Sony ZX330BT',
        img: './ProductImages/headphones.png',
        Price: 39.99,
        Des: "So easy-lightweight, compact listening with added wireless freedom. Enjoy your favorite beats with cord-free convenience via Bluetooth with Near Field Communications (NFC) technology. Envelope yourself in full, balanced sound and tight beats with 30mm drivers and easily swivel and stow away when done.",
    },
    {
        id: iphone12,
        Title: 'iPhone 12',
        img: './ProductImages/iphone-12-01.png',
        Price: 619.99,
        Des: "5G speed. A14 Bionic, the fastest chip in a smartphone. An edge-to-edge OLED display. Ceramic Shield with four times better drop performance. And Night mode on every camera. iPhone 12 has it all.",
    },
    {
        id: macbook,
        Title: 'MacBook',
        img: './ProductImages/macbook.png',
        Price: 201,
        Des: "The MacBook Pro is a line of Mac laptop computers developed and manufactured by Apple. Introduced in January 2006, it is the higher-end lineup in the MacBook family, sitting above the consumer-focused MacBook Air. It is currently sold with 14-inch and 16-inch screens, all using Apple silicon M-series chips.",
    },
    {
        id: dellXps13,
        Title: 'Dell XPS 13',
        img: './ProductImages/Name=Dell-XPS-13-Black.png',
        Price: 201,
        Des: "Description goes here",
    },
    {
        id: iphone13,
        Title: 'iPhone 13',
        img: './ProductImages/Name=Iphone-13-Pro-01.png',
        Price: 201,
        Des: "iPhone 13. The most advanced dual-camera system ever on iPhone. Lightning-fast A15 Bionic chip. A big leap in battery life. Durable design. Superfast 5G. And a brighter Super Retina XDR display.",
    },
    {
        id: note21,
        Title: 'Samsung Galaxy Note 21',
        img: './ProductImages/Name=Samsung-Note21.png',
        Price: 201,
        Des: "The Samsung Galaxy Note 20 and Galaxy Note 20 Ultra are a series of high end Android-based phablets designed, developed, produced and marketed by Samsung Electronics as part of  their Samsung Galaxy Note Series, succeeding the Galaxy Note 10 series.",
    },
    {
        id: s21Ultra,
        Title: 'Samsung Galaxy S21 Ultra',
        img: './ProductImages/Name=Samsung-S21-Pro.png',
        Price: 201,
        Des: "Description goes here",
    },
    {
        id: s21,
        Title: 'Samsung Galaxy S21',
        img: './ProductImages/Name=Samsung-S21.png',
        Price: 201,
        Des: "The Samsung Galaxy S21 is an Android phone manufactured and distributed by Samsung Electronics. It comes with a new camera module design and next gen smartphone processors.",
    },
]